<div id="bottombar">
  <div class="holder">
    <ul>
      <li><a href="#overview" class="boton">Qué es</a>
      </li>
      <li><a href="#lecciones" class="boton">Lecciones</a>
      </li>
      <li><a href="#especificaciones" class="boton">Contenidos</a>
      </li>
      <li><a href="#equipo" class="boton">Equipo</a>
      </li>
      <li><a href="#testimonios" class="boton">Testimonios</a>
      </li>
      <div class="float-none"></div>
    </ul>
  </div>
</div>