<div id="footer-wrapper">
  <div class="menu-footer-container">
    <ul id="menu-footer-menu" class="page-menu-wrapper-footer">
      <li id="menu-item-98791" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-98791"><a href="#" class="show-suscribe">Newsletter</a>
      </li>
      <li id="menu-item-89209" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-89209"><a href="mailto:hello@sexy-english.com">Contacto</a>
      </li>
    </ul>
  </div>
  <ul id="footer-container-right">
    <li class="copyright">Copyright ©2013 <a href="http://sexy-english.com/" title="Sexy English" class="on">Sexy English</a>. Todos los derechos reservados.</li>
  </ul>
</div>
<audio autoplay="autoplay">
  <source src="custom-pages/sexyenglish/common-files/media/sexy.mp3" />
  <source src="custom-pages/sexyenglish/common-files/media/sexy.ogg" />
</audio>
<script src="//static.getclicky.com/js" type="text/javascript"></script>
<script type="text/javascript">
try
{
  clicky.init(100688099);
}
catch (e)
{}
</script>
<noscript>
  <p>
    <img alt="Clicky" width="1" height="1" src="//in.getclicky.com/100688099ns.gif" />
  </p>
</noscript>
<script>
(function(i, s, o, g, r, a, m)
{
  i['GoogleAnalyticsObject'] = r;
  i[r] = i[r] || function()
  {
    (i[r].q = i[r].q || []).push(arguments)
  }, i[r].l = 1 * new Date();
  a = s.createElement(o),
  m = s.getElementsByTagName(o)[0];
  a.async = 1;
  a.src = g;
  m.parentNode.insertBefore(a, m)
})(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
ga('create', 'UA-46653595-1', 'sexy-english.com');
ga('send', 'pageview');
</script>