<section class="video">
  <div class="fondo-rosa"></div>
  <div id="bgVideo" class="background"></div>
  <div class="holder">
    <div class="container centrador">
      <img src="images/icono.png" alt="" class="icono" />
      <img src="images/logo.png" alt="" />
      <h6>Learning</h6>
    </div>
    <div class="browser oculto">
      <div class="browser-contents">
        <div class="slide-01">
          <h4>Learn <b>English...</b><br/>Be <b>Sexy!</b></h4>
          <img src="images/corazon.png" alt="" />
        </div>
        <div class="slide-02 oculto">
          <h4>El método más <b>revolucionario</b><br/>de <b>aprendizaje de inglés</b></h4>
          <img src="images/diplomado.png" alt="" />
        </div>
        <div class="slide-03 oculto">
          <h4>Pronto inauguraremos <b>Sexy English</b><br/><b class="show-suscribe">Suscríbete </b>a nuestra lista de espera</h4>
          <img src="images/calendar.png" alt="" class="show-suscribe" />
        </div>
      </div>
      <img src="images/browser.png" alt="browser" class="fondo-browser" />
    </div>
  </div>
</section>