<section id="equipo" class="samples">
  <div class="details">
    <div class="cont">
      <img src="images/equipo.png" alt="" class="icono" />
      <h1>Equipo directivo</h1>
    </div>
  </div>
  <div class="holder">
    <ul>
      <li class="first">
        <div style="background-image:url(&quot;images/team/concha.jpg&quot;)" alt="" class="img"></div>
        <h3>Concha Castillejo</h3>
        <p>CEO & Founder</p>
        <p><a href="http://www.linkedin.com/pub/concha-castillejo/b/b76/108/en" target="_blank"><i class="fa fa-linkedin-square"></i></a>
        </p>
      </li>
      <li class="second">
        <div style="background-image:url(&quot;images/team/simon.jpg&quot;)" alt="" class="img"></div>
        <h3>Simon Stepney</h3>
        <p>Content manager & Founder</p>
        <p><a href="http://es.linkedin.com/pub/simon-stepney/85/749/870" target="_blank"><i class="fa fa-linkedin-square"></i></a>
        </p>
      </li>
      <li class="third">
        <div style="background-image:url(&quot;images/team/enrique.jpg&quot;)" alt="" class="img"></div>
        <h3>Enrique Castillejo</h3>
        <p>Marketing manager & Founder</p>
        <p><a href="http://es.linkedin.com/pub/enrique-castillejo/2b/167/234" target="_blank"><i class="fa fa-linkedin-square"></i></a>
        </p>
      </li>
    </ul>
  </div>
</section>