<!DOCTYPE html>
<html lang="es">
  <head>
    <?php include 'views/head-meta.phtml' ?>
    <?php include 'views/head-statics.phtml' ?>
  </head>
  <body>
    <div class="presenation">
      <?php include 'views/topbar.phtml' ?>
      <?php include 'views/bottombar.phtml' ?>
      <?php include 'views/home/section-01-opening.phtml' ?>
      <?php include 'views/home/section-02-queEs.phtml' ?>
      <?php include 'views/home/section-03-enTuBolsillo.phtml' ?>
      <?php include 'views/home/section-04-lecciones.phtml' ?>
      <?php include 'views/home/section-05-contenidos.phtml' ?>
      <?php include 'views/home/section-06-suscribete.phtml' ?>
      <?php include 'views/home/section-07-social.phtml' ?>
      <?php include 'views/home/section-08-equipo.phtml' ?>
      <?php include 'views/home/section-09-testimonios.phtml' ?>
    </div>
    <?php include 'views/home/section-10-comentarios.phtml' ?>
    <?php include 'views/suscribe.phtml' ?>
    <?php include 'views/footer.phtml' ?>
  </body>
</html>