<section class="dof">
  <div class="holder">
    <div class="cont"><span style="-webkit-filter: blur(5px); filter: blur(5px);" class="text-block">Lecciones</span>
    </div>
  </div>
  <div class="background">
    <div class="cards layer1"></div>
    <div class="cards layer2"></div>
    <div class="cards layer3"></div>
  </div>
</section>
<section id="lecciones" class="samples">
  <div class="details">
    <div class="cont">
      <h1>Un aprendizaje emocional</h1>
      <p>Hemos diseñado un plan de estudios que te permitirá aprender y explorar el idioma desde un punto de vista emocional. El juego, la seducción, el intercambio de emociones, son la mejor base para el aprendizaje de un idioma.</p>
    </div>
  </div>
  <div class="holder">
    <ul>
      <li class="first">
        <h3>Tres niveles de dificultad</h3>
        <p><b>Good</b>, <b>Better</b>, <b>Best</b>. Ajustamos las lecciones según tus conocimientos del idioma.</p>
      </li>
      <li class="second">
        <h3>Objetivos claros</h3>
        <p>Nuestros cursos tienen como objetivo prepararte para superar pruebas de nivel oficiales internacionales.</p>
      </li>
      <li class="third">
        <h3>+18</h3>
        <p>¿Por qué +18? Porque somos adultos y aprendemos como adultos, Sexy English es un Método diseñado en exclusiva para nosotr@s.</p>
      </li>
    </ul>
    <div id="samples-grid" class="screenshots">
      <div class="screen">
        <div class="proximamente hidden-xs">
          <p>Próximamente</p>
        </div>
        <img alt="" src="images/thumbs/01.png" />
        <div class="info-sample">
          <h4>Women's handbags</h4>
          <p>What's really in them?</p>
        </div>
      </div>
      <div class="screen double">
        <div class="proximamente hidden-xs">
          <p>Próximamente</p>
        </div>
        <img alt="" src="images/thumbs/04.png" />
        <div class="info-sample">
          <h4>Blind dates: all you need to know</h4>
          <p>Conversation exercise</p>
        </div>
      </div>
      <div class="screen">
        <div class="proximamente hidden-xs">
          <p>Próximamente</p>
        </div>
        <img alt="" src="images/thumbs/02.png" />
        <div class="info-sample">
          <h4>Recommendable men/women vs toxic men/women</h4>
          <p>We take a closer look at personality types</p>
        </div>
      </div>
      <div class="screen">
        <div class="proximamente hidden-xs">
          <p>Próximamente</p>
        </div>
        <img alt="" src="images/thumbs/03.png" />
        <div class="info-sample">
          <h4>SMS/WhatsApp</h4>
          <p>Vocabulary</p>
        </div>
      </div>
      <a href="" class="screen">
        <div class="proximamente hidden-xs">
          <p>Lectura complementaria</p>
        </div>
        <img alt="" src="images/thumbs/05.png" />
        <div class="info-sample">
          <h4>Would you visit a dark room on this platform?</h4>
          <p>Survey</p>
          <div class="boton">Lee una muestra</div>
        </div>
      </a>
      <div class="screen">
        <div class="proximamente hidden-xs">
          <p>Próximamente</p>
        </div>
        <img alt="" src="images/thumbs/06.png" />
        <div class="info-sample">
          <h4>Food & love</h4>
          <p>Composition</p>
        </div>
      </div>
      <a href="new-year.php" class="screen">
        <img alt="" src="images/thumbs/07.png" />
        <div class="info-sample">
          <h4>Sexy readings for Christmas</h4>
          <p>Culture</p>
          <div class="boton">Lee una muestra</div>
        </div>
      </a>
    </div>
  </div>
</section>