<section id="testimonios" class="samples">
  <div class="details">
    <div class="cont cabecera">
      <img src="images/testimonio.png" alt="" class="icono" />
      <h1>Testimonios</h1>
      <h5>Valoraciones de los alumnos de la versión beta de pruebas de Sexy English</h5>
    </div>
    <div class="cont">
      <div class="testimonio">
        <div style="background-image:url('images/testimonios/4.jpg');" class="img"></div>
        <div class="texto">
          <p>"Me ha encantado probar Sexy… me ha encantado ser sexy."</p>
          <h5>– Cristina</h5>
        </div>
        <div class="clear-both"></div>
      </div>
      <div class="testimonio floatright">
        <div style="background-image:url('images/testimonios/1.jpg');" class="img"></div>
        <div class="texto">
          <p>"Al principio no sabía muy bien lo que significaba y cómo era el método, pero realmente aprendes inglés.."</p>
          <h5>– Toni</h5>
        </div>
        <div class="clear-both"></div>
      </div>
      <div class="testimonio">
        <div style="background-image:url('images/testimonios/5.jpg');" class="img"></div>
        <div class="texto">
          <p>"Este método me está encantando, es divertido, muy efectivo y muy sexy."</p>
          <h5>– Ana</h5>
        </div>
        <div class="clear-both"></div>
      </div>
      <div class="testimonio floatright">
        <div style="background-image:url('images/testimonios/6.jpg');" class="img"></div>
        <div class="texto">
          <p>"Me ha encantado probarlo. ¿Habrá una comunidad de SexyEnglish?"</p>
          <h5>– María</h5>
        </div>
        <div class="clear-both"></div>
      </div>
      <div class="testimonio">
        <div style="background-image:url('images/testimonios/2.jpg');" class="img"></div>
        <div class="texto">
          <p>"Me ha parecido genial, habrá que ver cómo llega al público."</p>
          <h5>– Enrique</h5>
        </div>
        <div class="clear-both"></div>
      </div>
      <div class="testimonio floatright">
        <div style="background-image:url('images/testimonios/3.jpg');" class="img"></div>
        <div class="texto">
          <p>"Lo que más me ha gustado es que voy a preparar mi examen con este sistema y veo que efectivamente sus contenidos responden a lo que necesito y encima me divierto."</p>
          <h5>– José</h5>
        </div>
        <div class="clear-both"></div>
      </div>
    </div>
  </div>
</section>