<section id="equipo" class="samples">
  <div class="details">
    <div class="cont">
      <img src="images/equipo.png" alt="" class="icono" />
      <h1>Equipo directivo</h1>
    </div>
  </div>
  <div class="holder">
    <ul>
      <li class="columna">
        <div style="background-image:url(&quot;images/team/concha.jpg&quot;)" alt="" class="img"></div>
        <h3>Concepción Castillejo</h3>
        <p>CEO & Founder</p>
        <p class="descripcion">Con más de 23 años de trayectoria y de nacionalidad española, es abogado MBA por la Universidad Antonio de Nebrija además de grado de suficiencia investigadora. Después de haber ocupado diferentes puestos en la alta dirección y trabajado para
          compañías multinacionales, dirige desde hace cinco años sus propios proyectos empresariales.</p>
        <p><a href="http://www.linkedin.com/pub/concha-castillejo/b/b76/108/en" target="_blank"><i class="fa fa-linkedin-square"></i></a>
        </p>
      </li>
      <li class="columna">
        <div style="background-image:url(&quot;images/team/simon.jpg&quot;)" alt="" class="img"></div>
        <h3>Simon Stepney</h3>
        <p>Content Manager & Founder</p>
        <p class="descripcion">De nacionalidad británica, vivió en USA durante más de quince años. Ha desarrollado su carrera profesional en España y Alemania fundamentalmente, como profesor especializado en la mejora de competencias en el idioma inglés de altos directivos
          de empresas públicas y privadas y en el ámbito de la traducción y locución. Tiene más de 30 años de experiencia en el mundo empresarial, donde ha ocupado diversos puestos directivos, ocupando en la actualidad el puesto de CEO de su propia empresa,
          en la que se realizan traducciones de altísima calidad en más de once idiomas.</p>
        <p><a href="http://es.linkedin.com/pub/simon-stepney/85/749/870" target="_blank"><i class="fa fa-linkedin-square"></i></a>
        </p>
      </li>
      <li class="columna">
        <div style="background-image:url(&quot;images/team/enrique.jpg&quot;)" alt="" class="img"></div>
        <h3>Enrique Castillejo</h3>
        <p>Pedagogics Director & Founder</p>
        <p class="descripcion">De nacionalidad Española, es Presidente del Colegio de Pedagogos, Presidente del Instituto de Calidad Pedagógica. Con más de 15 años de carrera profesional, es un especialista en marketing educativo, motivación y desarrollo de las claves del aprendizaje
          adulto. Desarrolla su actividad es España y América.</p>
        <p><a href="http://es.linkedin.com/pub/enrique-castillejo/2b/167/234" target="_blank"><i class="fa fa-linkedin-square"></i></a>
        </p>
      </li>
    </ul>
  </div>
</section>