<div id="bottombar">
  <div class="holder">
    <ul>
      <li><a href="index.php#overview" class="boton">Qué es</a>
      </li>
      <li><a href="index.php#lecciones" class="boton">Lecciones</a>
      </li>
      <li><a href="index.php#especificaciones" class="boton">Contenidos</a>
      </li>
      <li><a href="index.php#equipo" class="boton">Equipo</a>
      </li>
      <li><a href="index.php#testimonios" class="boton">Testimonios</a>
      </li>
      <div class="float-none"></div>
    </ul>
  </div>
</div>