<!DOCTYPE html>
<html lang="es">
  <head>
    <?php include 'views/head-meta.phtml' ?>
    <?php include 'views/head-statics.phtml' ?>
  </head>
  <body id="blog">
    <div class="presenation">
      <?php include 'views/blog/topbar.phtml' ?>
      <?php include 'views/blog/bottombar.phtml' ?>
      <?php include 'views/blog/new-year-text.phtml' ?>
    </div>
    <?php include 'views/suscribe.phtml' ?>
    <?php include 'views/blog/footer.phtml' ?>
  </body>
</html>